# Generated by Django 4.2.4 on 2023-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0003_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='output_text',
            field=models.TextField(default=''),
        ),
    ]
