# Generated by Django 4.2.6 on 2023-11-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0004_filter_output_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='item_descrip_string',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='filter',
            name='item_title_string',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='filter',
            name='openai_descrip_string',
            field=models.TextField(default=''),
        ),
    ]
