# Generated by Django 4.2.4 on 2023-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0004_filter_output_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='test_text',
            field=models.TextField(default=''),
        ),
    ]
