# Generated by Django 4.2.4 on 2023-11-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0007_remove_filter_output_text_filter_item_title_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='item_title_array',
        ),
        migrations.AddField(
            model_name='filter',
            name='output_text',
            field=models.TextField(default=''),
        ),
    ]
