# Generated by Django 4.2.4 on 2023-11-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0005_filter_item_descrip_string_filter_item_title_string_and_more'),
        ('bestow', '0008_remove_filter_item_title_array_filter_output_text'),
    ]

    operations = [
    ]
