# Generated by Django 4.2.7 on 2023-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0010_filter_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='nature',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filter',
            name='personality',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='activity_level',
            field=models.CharField(max_length=300),
        ),
    ]
