# Generated by Django 4.2.7 on 2024-01-11 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0011_filter_nature_filter_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
