# Generated by Django 4.2.7 on 2024-01-12 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0015_alter_filter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
