# Generated by Django 4.2.7 on 2024-01-12 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0017_alter_filter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 16, 39, 56, 719534)),
        ),
    ]
