# Generated by Django 4.2.7 on 2024-01-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0020_alter_filter_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='user',
            new_name='user_id',
        ),
    ]
