# Generated by Django 4.2.7 on 2024-01-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0021_rename_user_filter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='user_id',
            new_name='user',
        ),
    ]
