# Generated by Django 4.2.7 on 2024-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0022_rename_user_id_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
