# Generated by Django 4.2.7 on 2024-01-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0023_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
