# Generated by Django 4.2.7 on 2024-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestow', '0029_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='giftee_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
